### ISSUE TITLE
`org-ml-update` does change point even when wrapped with `(save-excursion FORM)`

### ISSUE THREAD

**Issue by hrehfeld** [ndwarshuis/om.el#18]
``` .org
* Foo Bar
#  doesn't change point
# (org-ml-update* (identity it) (org-ml-parse-this-headline))

# changes point to beginning of * Foo
# (org-ml-update* (org-ml-headline-set-node-property "title" "test" it) (org-ml-parse-this-headline)) 

# changes point to beginning of * Foo
# (save-excursion (org-ml-update* (org-ml-headline-set-node-property "title" "test" it) (org-ml-parse-this-headline)))
```
I sortof understand why this might happen, however it would be awesome to have better behavior here.

Doesn't org-mode have some sort of logic to save & find context around links? Maybe we can hijack that, otherwise it might be possible to save a priority queue of things to jump to near point.

**Comment by ndwarshuis** [comment]
The reason that happens is because `org-ml-update` deletes and re-inserts text for the entire node, so even `save-excursion` wouldn't be valid since the point it is saving may no longer exist (imagine what would happen if you wanted to delete the headline title).

One way to workaround this would be to wrap the entire `org-ml-update` call in a `let` binding that caches the current point, but note this will only do what you want if the text from the beginning of the target node to the current point isn't changing:

``` lisp
(let ((cur (point)))
  (org-ml-update* (org-ml-headline-set-node-property "title" "test" it) (org-ml-parse-this-headline))
  (goto-char cur))
```

I'm not sure what you meant in the last paragraph. Can you name a function/macro that does what you are thinking?

I agree this is annoying and one way to solve it would be to somehow perform a diff on the old vs new node and only change the text that needs to be changed; adding that logic would be more complicated and would also probably be slower which is why it isn't in the package (at least not yet, I actually considered this early in the design process).

**Comment by hrehfeld** [comment]
> I'm not sure what you meant in the last paragraph. Can you name a function/macro that does what you are thinking?

I was thinking along the lines of (*completely untested code*):

```emacs-lisp
(let ((search-limit 50)
      (cur (point))
      (cur-word (word-at-point t)))
  ;; save next word context
  (forward-to-word)
  (let* ((after-word (word-at-point t))
         (after-offset (- cur (point))))
    (goto-char cur)
    ;; save previous word context
    (backward-to-word)
    (let ((before-word (word-at-point t))
          (before-offset (- (point) cur)))
      ;; modify contenst of buffer
      (org-ml-update* (org-ml-headline-set-node-property "title" "test" it) (org-ml-parse-this-headline))
      ;; try old position in case nothing changed
      (goto-char cur)
      (if (string-equal (word-at-point t) cur-word)
          ;; if on the same word, try to readjust point to same position
          (progn (forward-to-word)
                 (goto-char (- (point) after-offset)))
        (progn
          ;; search forward for after-word
          (if (word-search-forward after-word (+ cur after-offset search-limit) t)
              ;; try to readjust point to same position via offsets
              (progn (forward-to-word)
                     (goto-char (+ (point) after-offset)))
            ;; if fails, search forward for before-word
            (if (word-search-backward before-word (- cur before-offset search-limit) t)
                ;; try to readjust point to same position via offsets
                (progn (backward-to-word)
                       (goto-char (- (point) before-offset))))
            ;;give up
            ))))))
```
