### ISSUE TITLE
Source block parameters are tricky to access

### ISSUE THREAD

**Issue by nlander** [ndwarshuis/om.el#24]
Given two source blocks with a tangle parameter, accessing the tangle parameter is quite different depending on if it is found in a HEADER or on the BEGIN_SRC line.
As a minimal example, here is the contents of an org file named org-ml-header-bug-minimal-example.org with the following contents:
```
#+TITLE: Org Ml Header Bug Minimal Example
* A code block with a tangle argument in a HEADER
#+HEADER: :tangle ~/path/to/hello-org-ml.el
#+BEGIN_SRC emacs-lisp
(message "%s" "hello org-ml")
#+END_SRC
* A code block with a tangle argument on the BEGIN_SRC line
#+BEGIN_SRC emacs-lisp :tangle ~/path/to/hello-org-ml.el
(message "%s" "hello org-ml")
#+END_SRC
```
I can access the tangle parameter of the second source block in the following way:
```
ELISP> (save-excursion (set-buffer "org-ml-header-bug-minimal-example.org") (org-ml-parse-element-at 316))
(src-block
 (:language "emacs-lisp" :switches nil :parameters ":tangle ~/path/to/hello-org-ml.el" :begin 261 :end 358 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :value "(message \"%s\" \"hello org-ml\")
" :post-blank 0 :post-affiliated 261 :parent nil))

ELISP> (org-ml-get-property :parameters *)
(:tangle ~/path/to/hello-org-ml\.el)

ELISP> (plist-get * :tangle)
~/path/to/hello-org-ml\.el
ELISP> (with-temp-file * (insert "hello org-ml"))
*** Eval error ***  Wrong type argument: stringp, ~/path/to/hello-org-ml\.el
ELISP> (symbol-name *)
"~/path/to/hello-org-ml.el"
ELISP> (with-temp-file * (insert "hello org-ml"))
nil
```
Whereas with the first block, where the tangle parameter is in the header, I can access the tangle parameter like this:
```
ELISP> (save-excursion (set-buffer "org-ml-header-bug-minimal-example.org") (org-ml-parse-element-at 160))
(src-block
 (:language "emacs-lisp" :switches nil :parameters nil :begin 94 :end 201 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :value "(message \"%s\" \"hello org-ml\")
" :post-blank 0 :post-affiliated 138 :header
(":tangle ~/path/to/hello-org-ml.el")
:parent nil))

ELISP> (org-ml-get-property :header *)
*** Eval error ***  Argument type error: "Type ’src-block’ does not have property ’:header’"
ELISP> (org-ml--get-property-nocheck :header *)
(":tangle ~/path/to/hello-org-ml.el")

ELISP> (car *)
":tangle ~/path/to/hello-org-ml.el"
ELISP> (s-chop-prefix ":tangle " *)
"~/path/to/hello-org-ml.el"
ELISP> (with-temp-file * (insert "Hello org-ml"))
nil
```
It would be nice if there was a function for consistently getting a source block parameter regardless of whether or not that parameter is in a HEADER. At a more granular level, it would be nice if source block parameters were consistently parsed as either plists of symbols or lists of strings, but not both depending on where it is specified. It would also be preferable for `org-ml-get-property` to not throw an error when accessing the `:header` property of a source block.

I realize this stuff may not be trivial to change in a way that makes sense for the overall functionality of this library, and I completely understand if you don't want to spend time on this. This library is generally great to work with, so thank you for all your hard work putting it together!

**Comment by ndwarshuis** [comment]
Thanks for pointing this out. I actually don't use src-blocks all that often so TBH this part of the library didn't get as much attention as others.

There seems to be 3 issues:

#### throwing error when accessing :header

Easy to fix. This is meant to help catch mistakes for the user since accessing a non-existent property will return nil (at low level it's just `plist-get`), which is ambiguous since nil should represent lack of a value in an existing property vs failure to find said property. I forgot to add affiliated keywords (of which `:header` is one) to the list of "accepted" properties. This just means that you can't use `org-ml-get-property` and friends, but `org-ml-get-affiliated-keyword` should work as a workaround.

#### plist in :header is actually a string

This is where I need feedback since I almost never use affiliated keywords myself in general. I can parse the `:header` string to a plist and return that, but this only makes sense if the `#+HEADER` affiliated keyword will ALWAYS hold a serialized plist. Looking at the org-mode manual this seems to be the intended use case, but there is almost no discussion about how this is standardized and I'm not sure how third-party packages may use it either.

#### common interface for getting src-block parameters

This depends on what you call a common interface. I agree that presenting a plist consistently would be ideal, but adding a function to return the src-block parameters regardless of where they are sounds like it would just amount to `(append (org-ml-get-property :header *) (org-ml-get-property :parameters *))` (assuming those both return plists and don't throw errors). IMHO this function is easy enough for an end user to construct themselves.

The reason why this matters is because as a general rule I designed the library to have symmetric 'get' and 'set' functions (eg `(org-ml-set-property :foo (org-ml-get-property :foo *) *)` should be the same as `(identity *)`). In this case, if we have a 'get' operation that concatenates two different properties, there is no obvious way to have a 'set' operation since it isn't clear how to allocate the parameter plist among the `:header` and `:parameters` properties.

Is this the kind of interface you were after or did I miss something?

**Comment by nlander** [comment]
Thanks for this detailed and thoughtful reply!

My ideal interface for source blocks would be that I can simply use `(org-ml-get-property :tangle *)` and `(org-ml-set-property :tangle "/some/file/path/" *)` for `:tangle` and any other valid source block parameters.

I think there are multiple ways this could be achieved, but all of them have something tricky to them. What seems most elegant in my mind is that source block parameters are parsed such that they are properties of the source block. This makes it so that `org-ml-get-property` and `org-ml-set-property` could work unmodified, while the parsing and building functions would need significant changes. In order to build the same org file that was parsed we would need another property specifying the location of the source block parameter. I am really not sure how much work it would take to make this work well.

**Comment by ndwarshuis** [comment]
> What seems most elegant in my mind is that source block parameters are parsed such that they are properties of the source block.

If the idea is to somehow merge the `:header` and `:parameters` properties into one meta-property at the node-level, this isn't going to be feasible. I don't touch `org-element`'s representation of a 'node' for compatibility reasons (and `org-element` is a central component to org-mode itself). Not sure if this is a source of confusion, but `org-ml` doesn't do the parsing; that's all performed by `org-element`.

However, I don't think `org-element` parses org syntax in a way that is most convenient for the intended use cases of `org-ml`. To circumvent this, `org-element-get-property` will do on-the-fly conversions. In the case you identified, the `:parameters` property is actually the string `":tangle ~/path/to/hello-org-ml.el"` when stored in the src-block node, but converted to a plist when you call `(org-ml-get-property :parameters *)`. This is the part that's currently broken for the `:header` property since it just presents the plist without converting it and/or throws an unnecessary error.

The interface you seem to be proposing is actually one layer above this, which will perform on-the-fly conversion and merging/separating of multiple properties (which `org-ml-get/set-property` isn't meant to do). I'm not opposed to adding a new function for this since it already has precedence (example: `org-ml-timestamp-set-start-time`). However, in order to prevent this library from becoming bigger than it already is, I want to make sure that this couldn't be solved much easier with existing functions (such as `append` and `org-ml-get-property`).

Otherwise, the interface you would want given the constraints would be something like `(org-ml-get-tangle *)` where the output would be a new data structure like `(:header plist1 :parameters :plist2)` which determines how the plists are spread across the `:header` and `:parameters` properties (and then the 'set' operation would consume said data structure).
