### ISSUE TITLE
in some cases (e.g org-link abbreviations) parsing functions don't preserve original text

### ISSUE THREAD

**Issue by dannyob** [ndwarshuis/om.el#3]
Hello!
I love `om.el`, but I've hit one problem that might be a bug.
I use [org-link abbreviations](https://orgmode.org/manual/Link-abbreviations.html) in my orgmode files, where an initial keyword in a link, followed by a colon, can cause the rest of the link to be converted or changed before the link is followed. So "wiki:blah" as a link could end up taking the user to a "~/txt/wiki/blah.org" file instead. The transformations are defined in [org-link-abbrev-alist](https://orgmode.org/manual/Link-abbreviations.html).

When I'm parsing one of these files, this link destination is expanded in the parsed results -- which means that if I use that value to update the current file, the original abbreviation is changed into its fully expanded form. That means that updating can create a side-effect of expanding these links. 

Here's a small test-case which I think works on its own:
```elisp
(let ((test-org "Hello [[test:foo]]")
      (org-link-abbrev-alist '(("test" . "i-am-transformed-from-"))))
     (with-temp-buffer
      (insert test-org)
      (om-to-trimmed-string (om-parse-this-element))))

As you should hopefully see, the result doesn't match the input.



```

**Comment by ndwarshuis** [comment]
So if I'm understand correctly, you don't expect the abbreviations to update when parsed/printed using `om.el` functions?

This behavior is actually expected based on `org-element.el`; the function `org-element-link-parser` calls the function `org-link-expand-abbrev` which handles the abbreviation replacements. The latter function does nothing if `org-link-abbrev-alist` or `org-link-abbrev-alist-local` are nil. `om.el` currently does nothing to override either of these variables, so this is the source of the behavior you are seeing.

**Comment by dannyob** [comment]
That makes sense, thank you.

I guess I was expecting these functions to preserve the original content, because I was anticipating using om-update in a pure/functional way -- running a set of functions over the parsed content, and then replacing the whole structure in the original document. I guess that abstraction doesn't quite work with org-element.el underlying om.el.

**Comment by ndwarshuis** [comment]
Yup, that's frustrating but thank you for reporting it. There are actually quite a few instances in `org-element` like this where input =/= output (there's a few workarounds in `om.el` to smooth over these inconsistencies).

This one is a bit different because the behavior depends on a variable being set, so for now the workaround is just to use a local let binding like the OP (except with nil) to get the functional behavior. I might build this into `om.el` in the future, but I also suspect there are other cases like this in `org-element` that I haven't found yet so that may not be practical.

For now I'll keep this issue open until I figure out the best way to resolve it.

**Comment by dannyob** [comment]
That's a great workaround, thank you. I've changed the title of this issue to make it more general, so it can act a placeholder for these cases.
