### ISSUE TITLE
Semantics of :parent and ways to reparent/orphan nodes

### ISSUE THREAD

**Issue by pgroce** [ndwarshuis/om.el#31]
I'm writing code that extracts elements from a number of org-mode buffers and writes new elements based on them into a new buffer. I've encountered two places where I've wanted to change the parent:

 * It is sometimes natural to clone a section (say) from one tree and add it as a child to another tree. In this case, it would seem prudent to reparent the cloned node to its new parent
 * I like to print the actual object sexps during debugging, and in those situations, it's much easier to see the structure of the tree when the node's parent is set to, say, `nil`.

This led me to look for ways to reparent/orphan elements/objects in the API, but this doesn't seem to be supported, and in some cases is specifically disallowed. (`Property ’:parent’ is unsettable for type ’headline’` when trying to set `:parent` with `org-ml-set-property`, for instance.)

I assume you have reasons for this; I was wondering what those are. Is there a semantic difference between the node referred to by the `:parent` property and whichever org-element list a node is currently enclosed in? Are there approved ways to create a node from the content of another node, but with a different/empty `:parent` property?

Sorry if this is already documented; I looked, but didn't come across anything. Thanks for humoring my curiosity, and thanks for this outstanding library.

**Comment by pgroce** [comment]
Not five seconds after I hit submit I find this on the front page:

> The properties :begin, :end, :contents-begin, :contents-end, :parent, and post-affiliated are not settable by this API as they are not necessary for manipulating the textual representation of the parse tree. 

Sigh.

Can `:parent` can be safely ignored, then? And if so, can I just use `delq` and friends to remove `:parent` and Things Will Be Fine? (I probably won't do this except for displaying debug info, so this is probably a moot point, but if you have thoughts on it, I'd be curious to hear them.)

**Comment by ndwarshuis** [comment]
I essentially think of the `:parent` property as a read-only value that only matters when parsing a buffer. If you actually care about what the value of `:parent` is after parsing, there is `org-ml-get-parents` and `org-ml-get-property` (for which `:parent` is allowed, unlike the `set` analogue).

To be more specific, using `org-ml-parse-X` (or equivalent) will produce a node/tree with the `:parent` property set. Going in the other direction using `org-ml-to-string`, `:parent` is ignored. This is true for `org-element` itself since this is how `org-element-interpret-data` works. The only thing that matters when converting a node to a string is the structure of the tree itself (eg what nodes are enclosed by other nodes) and then a handful of properties that are read by the string converter. This is why I made `:parent` unsettable and is also why building a new node with `org-ml-build-X` will keep the `:parent` property set to nil.

To make things admittedly more confusing, `:parent` is far from the only property that works like this. For example, `:raw-value` for headlines is also totally ignored when converting to a string via `org-element`. In this case it uses the `:title` property which is a list representation of `:raw-value`. It would theoretically be possible to 'set' `:raw-value` to a some string and then actually change the `:title` property, but this seemed overly complex when I wrote the library. Furthermore, headlines have additional properties that track items in the `:PROPERTIES:` drawer (also not read by the string converter). Again, it is theoretically possible to make `org-set-property :EFFORT` actually set the `EFFORT` for a headline, but that's what `org-ml-headline-set-node-property` is for. To me it seemed overly complicated to make multiple ways of doing the same thing, so I  restricted the properties that could be set to the ones that are actually read by the string converter (hence the 'unsettable' error messages).

I would be open to changing the error messages and/or docs to reflect this better (not quite sure how but feedback welcome) since the `org-ml` 'API' requires a fair bit of understanding of `org-element` itself in order to use as it stands.

> Can :parent can be safely ignored, then?

Yes, although I personally would use `plist-put` just to ensure that the property plist still has a key called `:parent` (I'm not sure if that's necessary, but it's a safer assumption).

> It is sometimes natural to clone a section (say) from one tree and add it as a child to another tree. In this case, it would seem prudent to reparent the cloned node to its new parent

Is there a reason `org-ml-set-children` won't work for this (if not it would help to see example code of what the function you want would do)? It's effectively the same thing from an inverted perspective.

> I like to print the actual object sexps during debugging, and in those situations, it's much easier to see the structure of the tree when the node's parent is set to, say, nil.

I completely agree with this and would be willing to add a function that runs through the tree and nil's all parents.

**Comment by pgroce** [comment]
Thanks! I suspected something like this was going on based on what I had seen so far, but it's helpful to have that understanding confirmed and expanded on like this.

> I would be open to changing the error messages and/or docs to reflect this better (not quite sure how but feedback welcome) since the `org-ml` 'API' requires a fair bit of understanding of `org-element` itself in order to use as it stands.

I suspect I'm where you are–a lot of this would benefit from more explanation of the underlying structure, but that seems like a significant expansion of scope. It doesn't help that (AFAICT) the Org project treats the AST as an implementation detail and not any kind of standard format.

That said, I have a suggestion for a smaller change below.

> Is there a reason `org-ml-set-children` won't work for this

So far I've been using the `org-ml-build-*`  functions, many of which take their children as arguments. `org-ml-set-children` would work fine too, AFAICT. I was just confused because doing so didn't seem to change the `:parent` property of the children, even though they had new "parents." I think I understand what's going on better now.

> I completely agree with this and would be willing to add a function that runs through the tree and nil's all parents.

That would be a worthy addition to the library, IMO. It would certainly make my life easier. :)

If you do this, you may want to include some of the material above on the nature of the `:parent` property in the description of this function. I think most people who need the information would eventually find it there.

**Comment by ndwarshuis** [comment]
See 4435cd5fc94c00f6e6054324a3e022ad0e37ae0f on the develop branch and let me know what you think.

**Comment by pgroce** [comment]
I haven't run the code, but on review it all looks good. The documentation, in particular, answers a lot of the questions I had about parents when I filed this issue.

My, but there are a lot of edge cases involved in org-element tree traversal.

**Comment by ndwarshuis** [comment]
Cool, it passes my (admittedly limited) tests so it should work. That being said, please test it yourself and let me know if anything crashes or if there are edge cases I missed. Some node types like to bury objects in weird places which worries me a bit.
