### ISSUE TITLE
recommended way to build a headline with properties?

### ISSUE THREAD

**Issue by jkitchin** [ndwarshuis/om.el#9]
Is this the recommended way to do that:

```
#+BEGIN_SRC emacs-lisp
(concat (->> (om-build-headline :todo-keyword "TODO" :archivedp t :commentedp t :priority 65)
	     (om-to-trimmed-string))
	"\n"
	(->>
	 (om-build-property-drawer! '(key val))
	 (om-to-trimmed-string)))
#+END_SRC
```

Is there a way to get the properties indented?

I thought the properties would be a child node of a headline, but that seems to be illegal.

**Comment by ndwarshuis** [comment]
That should work but you can also do this to add the property drawer directly to the headline node:
```lisp
(->> (om-build-headline :todo-keyword "TODO" :archivedp t :commentedp t :priority 65)
     (om-headline-set-node-property "key" "value")
     (om-to-string))
```

Should produce:
```
* TODO COMMENT [#A]                                                 :ARCHIVE:
:PROPERTIES:
:key:      value
:END:
```

Adding the drawer directly is illegal because headline nodes can only contain section nodes and other headline nodes as direct children. The section is a container for property drawers, other drawers, paragraphs, etc. That's a pain to add manually which is why `om-headline-set-node-property` exists (and others like it for planning and logbook).

This might be naive, but what do you mean by indenting the properties? I have org-indent enabled in my config to make it look indented, but I don't think there is a way to add space to the front using the functions in this package if that's what you mean.

**Comment by jkitchin** [comment]
Awesome, thanks!

If I was to make that by hand it would look like:
```

* TODO COMMENT [#A]                                                 :ARCHIVE:
  :PROPERTIES:
  :key:      value
  :END:
 
```

It isn't a super big deal I think.
